preview: release.png
	convert release.png -resize 512x512 -threshold 1% preview.png

release.png:
	../scripts/convert.py --delta 0.16 render.png release.png

# Note: render.png is obtained by running Apophysis with a bunch of plugins...
